name: D8 Code Review

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  code-standards:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        php_version: ['7.3']

    steps:
    - name: Check out code 
      uses: actions/checkout@v2
      with:
        fetch-depth: 1

    - name: Set up PHP ${{ matrix.php_version }}
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php_version }}

    - name: Install dependencies
      run: composer install --dev

    - name: Composer version
      run: composer -V

    - name: Install Coder
      run: composer global require drupal/coder:^8.3.1

    - name: Install Codesniffer
      run: composer global require dealerdirect/phpcodesniffer-composer-installer

    - name: List all of the available packages
      run: composer global show -P

    - name: Composer home directory
      run: composer config home

    - name: Verify Registered Standards
      run: ~/.composer/vendor/bin/phpcs -i

    - name: To check the path
      run: ls ~/.composer/vendor/drupal/

    - name: Manually Set Installed Paths
      run: phpcs --config-set installed_paths /home/runner/.composer/vendor/drupal/coder/coder_sniffer



    # Add a test script to composer.json, for instance: "test": "vendor/bin/phpunit"
    # Docs: https://getcomposer.org/doc/articles/scripts.md

    # - name: Run test suite
    #   run: composer run-script test
