name: D8 Code Review

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  code-standards:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
      with:
        fetch-depth: 1
      
    - name: Composer version
      run: composer -V

    - name: Install Coder
      run: composer global require drupal/coder:^8.3.1

    - name: Install Codesniffer
      run: composer global require dealerdirect/phpcodesniffer-composer-installer

    - name: Validate composer.json and composer.lock
      run: composer validate

    - name: Install dependencies
      run: composer install --prefer-dist --no-progress --no-suggest

    - name: List all of the available packages
      run: composer global show -P

    - name: Composer home directory
      run: composer config home

    - name: Path of phpcs
      run: which phpcs

    - name: Verify Registered Standards
      run: phpcs -i	
 
    - name: Manually Set Installed Paths
      run: phpcs --config-set installed_paths ~/.composer/vendor/drupal/coder/coder_sniffer

    # Add a test script to composer.json, for instance: "test": "vendor/bin/phpunit"
    # Docs: https://getcomposer.org/doc/articles/scripts.md

    # - name: Run test suite
    #   run: composer run-script test
